apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spoolman
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BryanSmee/3dprinter-infra.git
    targetRevision: main
    path: apps/spoolman
  destination:
    server: https://kubernetes.default.svc
    namespace: spoolman
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
