apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spoolman-data
  namespace: spoolman
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: ""  # Uncomment and set to pin a specific StorageClass.
