apiVersion: v1
kind: Service
metadata:
  name: spoolman
  namespace: spoolman
  labels:
    app.kubernetes.io/name: spoolman
spec:
  selector:
    app.kubernetes.io/name: spoolman
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
